### ISSUE TITLE
Error make app

### ISSUE THREAD

**Issue by Jnsll** [REGOVAR/regovar-server#25]
During the installation, when doing `make app`, i get the following error. I am in the virtualenv. 
It seems to be linked to `sample_variant_hg19`.
````
python annso_server.py
Traceback (most recent call last):
  File "/media/DATA/Projects/Annso/venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 210, in __getattr__
    return self._data[key]
KeyError: 'sample_variant_hg19'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "annso_server.py", line 10, in <module>
    from core.framework import AnnsoException
  File "/media/DATA/Projects/Annso/annso/core/__init__.py", line 6, in <module>
    from core.model import *
  File "/media/DATA/Projects/Annso/annso/core/model.py", line 50, in <module>
    SampleVariant = Base.classes.sample_variant_hg19
  File "/media/DATA/Projects/Annso/venv/lib/python3.6/site-packages/sqlalchemy/util/_collections.py", line 212, in __getattr__
    raise AttributeError(key)
AttributeError: sample_variant_hg19

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

make: *** [Makefile:11: app] Error 1

**Comment by ikit** [comment]
sqlalchemy base classes are not well initialized. Can you check database's connexion parameters in the config file ? are they correct ?

**Comment by Jnsll** [comment]
Here is my Annso/annso/config.py file. I don't see what could be wrong. (I only use the internal HOST for now so no need to change the `HOST_P = HOSTNAME` part yet.)
```
#!env/python3
# coding: utf-8 
import os


DEBUG = True


# HOST (internal)
HOST = "127.0.0.1"
PORT = "8100"
VERSION = "v1"
HOSTNAME = HOST + ":" + PORT + "/" + VERSION  # This is the internal host on which aioHTTP will run the service.


# HOST (public)
HOST_P = HOSTNAME  # THIS url must be change if the annso server is reach via a public namespace that user
RANGE_DEFAULT = 100
RANGE_MAX = 1000


# DB
DATABASE_HOST = "localhost"
DATABASE_PORT = "5432"
DATABASE_USER = "annso"
DATABASE_PWD = "ansso"
DATABASE_NAME = "annso"
DATABASE_POOL_SIZE = 7


# FILESYSTEM
FILES_DIR = "/var/regovar/annso/files"
TEMP_DIR = "/var/regovar/annso/downloads"
CACHE_DIR = "/var/regovar/annso/cache"


# MODULES ACTIVATED
EXPORTS_MODULES = []
IMPORTS_MODULES = ["vcf"]
REPORTS_MODULES = []


# AUTOCOMPUTED VALUES
ANNSO_DIR = os.path.dirname(os.path.abspath(__file__))
TEMPLATE_DIR = os.path.join(ANNSO_DIR, "api_rest/templates/")
ERROR_ROOT_URL = "api.annso.org/errorcode/"


# INTERNAL CONSTANT
EXPORTS_MODULES_PATH = "exports.{0}"
IMPORTS_MODULES_PATH = "imports.{0}"
REPORTS_MODULES_PATH = "reports.{0}.report"

DEFAULT_REFERENCIAL_ID = 2 # hg19
```

**Comment by ikit** [comment]
are you able to connect to your sql database with the command line tool and the credentials of the config file ?
`psql -U annso -d annso -W`

**Comment by Jnsll** [comment]
Yes, i'm able to connect to the sql database with `psql -U annso -d annso -W`. 
```
$ psql -U annso -d annso -W
Mot de passe pour l'utilisateur annso : 
psql (9.6.1)
Saisissez « help » pour l'aide.
annso=> 
```

**Comment by ikit** [comment]
ok, and then if you type the command \dt in the psql shell, what is the result ?

**Comment by Jnsll** [comment]
The result is :
```
annso=> \dt
                 Liste des relations
 Schéma |         Nom         | Type  | Propriétaire 
--------+---------------------+-------+--------------
 public | import_refgene_hg19 | table | annso
 public | refgene_exon_hg19   | table | annso
 public | refgene_hg19        | table | annso
 public | variant_hg19        | table | annso
(4 lignes)
```

**Comment by Jnsll** [comment]
I've found something that might be related. In the `annso/database/create_all.sql` file, at line 253 there's `ALTER TABLE public.variant_hg19 OWNER TO annso;`. And i think it should be `ALTER TABLE public.sample_variant_hg19 OWNER TO annso;` instead. But I may be wrong. What do you think ?

Edit: Nope, it did not change the error...

**Comment by ikit** [comment]
yes, you are right, but in your case the main problem is that you only have 4 tables instead of that :
``` Schema |          Name          | Type  |  Owner
--------+------------------------+-------+----------
 public | analysis               | table | annso
 public | analysis_sample        | table | annso
 public | annotation_database    | table | annso
 public | annotation_field       | table | annso
 public | attribute              | table | annso
 public | file                   | table | annso
 public | filter                 | table | annso
 public | parameter              | table | annso
 public | reference              | table | annso
 public | sample                 | table | annso
 public | sample_file            | table | annso
 public | sample_variant_hg19    | table | postgres
 public | template               | table | annso
 public | variant_hg19           | table | annso
```

You should try to drop the database, recreate it, and run again the create_all.sql script.
```psql -U postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'annso'"
psql -U postgres -c "DROP DATABASE annso"
psql -U postgres -c "CREATE DATABASE annso OWNER annso"
psql -U postgres -d annso -f create_all.sql
```

**Comment by Jnsll** [comment]
Well. I managed to solve the issue. In fact, it was again the collation which was the problem. I changed all the `COLLATE pg_catalog."C.UTF-8"` into `COLLATE pg_catalog."C" ` in the` /annso/database/create_all.sql` file and it did the trick. Sorry for the trouble caused.
